spring:
  application:
    name: zuul-gateway

zuul:
  ignored-services: '*'
  routes:
    helloworld:
      path: /api/helloworld/**
      service-id: HELLOWORLD-SERVICE
      strip-prefix: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

server:
  port: ${PORT:8100}